## Data Analysis Trade IronFX ('Broker')

## Objetivo

Encontrar un patron en los datos tal que pueda predecir que tipo de operaciones en divisas son más probables a ser ganadoras y entender cuál fue el problemas en los trades perdedores.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dft0=pd.read_csv('diario_trading_real.csv', decimal=',')
dft0

,Time_open,Type,Size,Symbol,Price_open,S/L,T/P,Time_close,Price_close,Swap,Profit,Comment,Unnamed: 12
0,2021/03/31 12:00:14,sell,0.01,gbpusd_M15,1.37986,1.38092,1.37825,2021/03/31 12:11:11,1.38092,0,-1.06,Me senti relajado,NaN
1,2021/03/31 12:31:33,buy,0.03,usdjpy_M15,110.657,110.53,110.71,2021/03/31 13:10:36,110.71,0,1.44,senti control,NaN
2,2021/03/31 12:33:46,sell,0.03,gpbusd_M5,1.37972,1.38072,1.37864,2021/03/31 13:24:21,1.37864,0,3.24,sentí control,NaN
3,2021/03/31 16:11:22,sell,0.03,usdjpy_M15,110.663,110.822,110.56,2021/03/31 18:08:40,110.822,0,-4.3,Senti relajado,NaN
4,2021/03/31 19:56:49,buy,0.03,usdchf_M30,0.94478,0.94357,0.94533,2021/03/31 11:23:01,0.94533,0,1.75,Senti control,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,2022/04/25 12:19:32,buy,0.01,uk100_m2_H1,7382,7322,7442,2022/04/26 1:00:03,7442,-0.03,7.65,Cabeza fría,NaN
331,2022/04/28 17:44:31,sell,0.01,usdjpy_H1,130.825,131.342,130.237,2022/04/29 1:23:21,130.237,0,4.51,Cabeza fria,NaN
332,2022/05/05 10:02:04,sell,0.01,wticash_H1,107.24,109.46,105.02,2022/05/05 16:28:07,109.46,-0.55,-22.2,Cabeza fría,NaN
333,2022/05/09 14:01:15,buy,0.01,ger40_m2_H1,13475,13336,13622,2022/05/10 3:38:38,13622,-0.05,38.83,Cabeza fría,NaN
334,2022/05/23 12:30:42,sell,0.01,nzdusd_H1,0.64566,0.64959,0.64173,2022/05/24 21:06:17,0.64959,-0.06,-3.93,Cabeza fría,NaN

In [4]:
dft0.drop('Unnamed: 12', inplace=True, axis=1)

In [5]:
dft0

,Time_open,Type,Size,Symbol,Price_open,S/L,T/P,Time_close,Price_close,Swap,Profit,Comment
0,2021/03/31 12:00:14,sell,0.01,gbpusd_M15,1.37986,1.38092,1.37825,2021/03/31 12:11:11,1.38092,0,-1.06,Me senti relajado
1,2021/03/31 12:31:33,buy,0.03,usdjpy_M15,110.657,110.53,110.71,2021/03/31 13:10:36,110.71,0,1.44,senti control
2,2021/03/31 12:33:46,sell,0.03,gpbusd_M5,1.37972,1.38072,1.37864,2021/03/31 13:24:21,1.37864,0,3.24,sentí control
3,2021/03/31 16:11:22,sell,0.03,usdjpy_M15,110.663,110.822,110.56,2021/03/31 18:08:40,110.822,0,-4.3,Senti relajado
4,2021/03/31 19:56:49,buy,0.03,usdchf_M30,0.94478,0.94357,0.94533,2021/03/31 11:23:01,0.94533,0,1.75,Senti control
...,...,...,...,...,...,...,...,...,...,...,...,...
330,2022/04/25 12:19:32,buy,0.01,uk100_m2_H1,7382,7322,7442,2022/04/26 1:00:03,7442,-0.03,7.65,Cabeza fría
331,2022/04/28 17:44:31,sell,0.01,usdjpy_H1,130.825,131.342,130.237,2022/04/29 1:23:21,130.237,0,4.51,Cabeza fria
332,2022/05/05 10:02:04,sell,0.01,wticash_H1,107.24,109.46,105.02,2022/05/05 16:28:07,109.46,-0.55,-22.2,Cabeza fría
333,2022/05/09 14:01:15,buy,0.01,ger40_m2_H1,13475,13336,13622,2022/05/10 3:38:38,13622,-0.05,38.83,Cabeza fría
334,2022/05/23 12:30:42,sell,0.01,nzdusd_H1,0.64566,0.64959,0.64173,2022/05/24 21:06:17,0.64959,-0.06,-3.93,Cabeza fría

In [6]:
dft0['Type'].unique()

array(['sell', 'buy', 'sell ', 'sel', 'buy '], dtype=object)

In [7]:
type1={'sell':'sell', 'buy':'buy', 'sel':'sell', 'buy ':'buy'}

In [8]:
dft0['Type']=dft0['Type'].map(type1)
dft0.groupby('Type').size()

Type
buy     164
sell    167
dtype: int64

Hay que tener en cuenta que durante un año de trading se realizarón más ordenes de venta que de compra

In [9]:
dft0['Symbol']

0       gbpusd_M15
1       usdjpy_M15
2        gpbusd_M5
3       usdjpy_M15
4       usdchf_M30
          ...
330    uk100_m2_H1
331      usdjpy_H1
332     wticash_H1
333    ger40_m2_H1
334      nzdusd_H1
Name: Symbol, Length: 335, dtype: object

podemos ver en la columna de "Symbol" que se encuentra el par de divisas que se realizo la operación junto con un distintivo M (minutos) y H (horas). Procederemos a realizar esa separación para tener más precisión en el análisis

In [21]:
dft0[['Symbol_only','temporality0','temporality1','temporality2']]=dft0['Symbol'].str.split('_', expand=True)
dft0

,Time_open,Type,Size,Symbol,Price_open,S/L,T/P,Time_close,Price_close,Swap,Profit,Comment,Symbol_only,temporality0,temporality1,temporality2
0,2021/03/31 12:00:14,sell,0.01,gbpusd_M15,1.37986,1.38092,1.37825,2021/03/31 12:11:11,1.38092,0,-1.06,Me senti relajado,gbpusd,M15,None,None
1,2021/03/31 12:31:33,buy,0.03,usdjpy_M15,110.657,110.53,110.71,2021/03/31 13:10:36,110.71,0,1.44,senti control,usdjpy,M15,None,None
2,2021/03/31 12:33:46,sell,0.03,gpbusd_M5,1.37972,1.38072,1.37864,2021/03/31 13:24:21,1.37864,0,3.24,sentí control,gpbusd,M5,None,None
3,2021/03/31 16:11:22,sell,0.03,usdjpy_M15,110.663,110.822,110.56,2021/03/31 18:08:40,110.822,0,-4.3,Senti relajado,usdjpy,M15,None,None
4,2021/03/31 19:56:49,buy,0.03,usdchf_M30,0.94478,0.94357,0.94533,2021/03/31 11:23:01,0.94533,0,1.75,Senti control,usdchf,M30,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,2022/04/25 12:19:32,buy,0.01,uk100_m2_H1,7382,7322,7442,2022/04/26 1:00:03,7442,-0.03,7.65,Cabeza fría,uk100,m2,H1,None
331,2022/04/28 17:44:31,sell,0.01,usdjpy_H1,130.825,131.342,130.237,2022/04/29 1:23:21,130.237,0,4.51,Cabeza fria,usdjpy,H1,None,None
332,2022/05/05 10:02:04,sell,0.01,wticash_H1,107.24,109.46,105.02,2022/05/05 16:28:07,109.46,-0.55,-22.2,Cabeza fría,wticash,H1,None,None
333,2022/05/09 14:01:15,buy,0.01,ger40_m2_H1,13475,13336,13622,2022/05/10 3:38:38,13622,-0.05,38.83,Cabeza fría,ger40,m2,H1,None
334,2022/05/23 12:30:42,sell,0.01,nzdusd_H1,0.64566,0.64959,0.64173,2022/05/24 21:06:17,0.64959,-0.06,-3.93,Cabeza fría,nzdusd,H1,None,None

In [23]:
dft0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Time_open     335 non-null    object
 1   Type          331 non-null    object
 2   Size          335 non-null    object
 3   Symbol        335 non-null    object
 4   Price_open    335 non-null    object
 5   S/L           335 non-null    object
 6   T/P           335 non-null    object
 7   Time_close    335 non-null    object
 8   Price_close   335 non-null    object
 9   Swap          335 non-null    object
 10  Profit        335 non-null    object
 11  Comment       335 non-null    object
 12  Symbol_only   335 non-null    object
 13  temporality0  334 non-null    object
 14  temporality1  88 non-null     object
 15  temporality2  22 non-null     object
dtypes: object(16)
memory usage: 42.0+ KB

En la lista anterior observamos que los registros que contienen tipo de dato numerico se encuntran categorizados como tipo objeto, realizamos una transformación a este tipo de datos para poder realizar la aritmetica correspondiente